syntax = "proto3";

package cmd.types;

import "google/protobuf/timestamp.proto";

option go_package = "cmd/proto/gen/go/pb;pb";

message Config {
  message Service {
    string host = 1;
    uint32 port = 2;
  }

  message Redisoptions {
    string addr = 1;
    string password = 2;
    uint32 db = 3;
  }

  Service gateway = 1;
  Service process = 2;
  Service gsio = 3;
  string dataSource = 4;
  Redisoptions redisOptions = 5;
  string fileDir = 6;
}

message Param {
  string inputName = 1;
  string inputValue = 2;
  string outputValue = 3;
  string name = 4; // 名称
  string inputType = 5; // 输入
  // string          outputType          = 6; // 输出
  float length = 7; // 长度
  string content = 8; // 内容
  // string          unit                = 9; // 单位
  // string          processMethod       = 10; // 处理方法
  // string          coefficient         = 11; // 当量系数
  repeated string physicalMeaningList = 12; // 物理意义列表
  // string          range               = 13; // 范围
  string repeatTimes = 14; // 重复次数
}

message CMD {
  string mark = 1; // 代号
  string subSystem = 2; // 分系统
  string packetName = 3; // 遥控包名称
  string pid = 4; // PID(b)
  string pcat = 5; // PCAT(b)
  string packetLength = 6; // 包长度
  string through = 8; // 通过标识
  string internal = 9; // 内务命令标识
  string virtualChannel = 10; // 虚拟信道识别字
  string code = 11; // 指令码(H)
  string form = 12; // 参数形式
  repeated Param paramList = 13; // 参数
  string outputValue = 14;
  string type = 15; // 上行遥控格式
  string user = 16; // 用户勤务字
  string mapID = 17; // 多路复用访问标识符
}

message CMDTask {
  CMD cmd = 1; // 指令
  bool filled = 2; // 是否装填
  string id = 3; // 任务id
  TaskType tasktype = 4; // 类型
  enum TaskType {
    Normal = 0;
    PlatForm = 1;
    Cplan = 2;
    Merge = 3;
  }
  string cplanID = 6; // cplanid
  string metaID = 7; // 元任务id
  string fillReq = 8; // 请求
  string client_ip = 9;
}

message CMDRecord {
  CMDTask cmdTask = 1; // 指令任务
  Status status = 2; // 状态
  enum Status {
    Succeed = 0; // 发送成功
    Failed = 1; // 发送失败
    CheckTeleMetryFailed = 2; // 遥测比对失败
    TimeOut = 3; // 发送超时
  }
  string sentAt = 4; // 发送时间
  CMDConf cmdConf = 5;
  string gsioSent = 6;
  string id = 7;
}

message CMDConf {
  Satellite satellite = 1;
  bool encrypted = 3; // 是否加密
  bool scrambled = 4; // 是否加扰
  Destination destination = 5;
}

message Satellite {
  string name = 1;
  google.protobuf.Timestamp epochTime = 2;
  string spacecraftValue = 3;
  bool checkMetry = 8; // 是否大环比对
  string excel = 10;
  FillType fillType = 12; // 装填类型
  SendType sendType = 13; // 发送类型
  string seqMark = 14; // 指令序列
  string fillTypeName = 15; // 装填类型名称
  string sendTypeName = 16; // 发送类型名称
  enum FillType {
    FILL_TYPE_UNSPECIFIED = 0;
    FILL_TYPE_CYDM = 1; // JGCY-遥控协议V1.0
    FILL_TYPE_MSC = 2; // MSC遥控帧格式1.1
    FILL_TYPE_ETRESS = 3; // ETRSS-2-CK-BG-02 埃塞俄比亚ETRSS-2卫星遥控数据格式约定（国外s）
    FILL_TYPE_ZHTW = 4; // TN1-03-CK-BG-02 智慧天网一号03星遥控数据格式约定
    FILL_TYPE_HY = 5; // 智能遥感计算卫星二号三号测控星地接口协议(国外x)弃用
    FILL_TYPE_ETRESSX = 6; // 埃塞ETRSS-2星X频段测控星地接口协议(国外x)弃用
    FILL_TYPE_GY = 7; // GY2-03-CK-BG-01 光音二号03星测控星地接口协议(国内x)弃用
    FILL_TYPE_QZ = 8; // 轻舟一号货运飞船遥测遥控格式约定
    FILL_TYPE_CCSDS_X = 9; // x
    FILL_TYPE_CCSDS = 10; // s
    FILL_TYPE_SCOE = 11; // 综合测试与对接机构模拟器间通信协议（公开）
  }
  enum SendType {
    SEND_TYPE_UNSPECIFIED = 0;
    SEND_TYPE_EMPOSAT = 1; // 驭星
    SEND_TYPE_AIRSAT = 2; // 中科卫星
    SEND_TYPE_SIS = 3; // sis
    SEND_TYPE_TRANSFORM = 4; // 地测
    SEND_TYPE_DIRECT = 5; // 直发
  }
}

message Destination {
  string name = 1;
  string value = 2;
  string label = 3;
}

message Cplan {
  string cplanID = 1;
  repeated Meta metaList = 2;
  string satelliteName = 3;
  message Meta {
    repeated CMD cmdList = 1;
    string metaID = 2;
  }
}
